import ThemeRegistry from "@/src/theme/ThemeRegistry";
import StoreProvider from "../lib/storeProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <ThemeRegistry>{children}</ThemeRegistry>
        </body>
      </html>
    </StoreProvider>
  );
}
